### ISSUE TITLE
Can you provide "Re-connect" feature like GUI version

### ISSUE THREAD

**Issue by andrewintw** [OpenNuvoton/NUC980_NuCWriter#1]
It's handy to have NuCWriter that supports CLI mode. But there's one more feature missing—Re-connect. When I use the GUI program, I just need to power on the first time by pressing the button and boot system from USB. Then I can do erase and program through the program of the GUI. However, the CLI mode NuCWriter needs to manually switch boot from USB before erase and before program, and does not have the "Re-connect" function like the GUI.

**Comment by ychuang3** [comment]
In the commit dated 2024-01-12, it has been modified so that every
time NuCWriter is executed, it will perform a reconnection process.
It detects the presence of the WinUSB device, and if found, it will
first perform a USB device reset before establishing the connection.
Therefore, you just need to repeatedly execute your desired
operations using a batch file.

**Comment by andrewintw** [comment]
Yes, as you said, I tested it again and it works as expected. Thanks 😃
